### ISSUE TITLE
Input image must have width of 5796 

### ISSUE THREAD

**Issue by zhLawliet** [timothybrooks/hdr-plus#10]
Input image must have width of 5796 ?
Input image must have height of 3870 ?

my image is 6024* 4024
i change the code
static const int width = 6024;
static const int height = 4024;
the result is bad? can you give me some suggests, thanks

**Comment by Trinkle23897** [comment]
@zhLawliet of course you can do this in the code, it runs well.
The author wrote with "static const" because this course assignment only provide with the same size of cr2 files

**Comment by zhLawliet** [comment]
thanks，Hello, can you provide cr2 files with multiple exposures? 5796 × 3870, I want to test the result of running cr2 normally. In addition, if I want to run Camera: google sailfish, I find that srgb_matrix needs to be changed, and dcraw doesn't see conversion parameters for google sailfish? Don't know if you understand? my e-mail is zhlawliet@qq.com thanks

**Comment by Trinkle23897** [comment]
@zhLawliet 你随便叫同学帮你用canon相机拍几张照片，然后直接把那个const height和width改成这些照片的长宽就完了呀……
dcraw对于google的照片显示是正常的，跑出来效果有问题是代码的锅

**Comment by timothybrooks** [comment]
You can change the width and height to whatever is appropriate for your images. The ideal thing to do would be to read the dimensions from the raw file's metadata--I only hard-coded these numbers out of convenience.

Feel free to email or message me privately if you would like for me to provide example raw images to process.

**Comment by zhLawliet** [comment]
@Trinkle23897 @timothybrooks 嗯，我找到了canon的照片，修改长宽后，程序运行结果没问题，主要是这个代码对标Google’s HDR+，我想用它运行google的照片，结果发现里面的转srgb空间的参数固定了，这个参数 在dcraw 的adobe_coeff 函数里面没有找到，不知道你们是怎么解决的？谢谢了。

**Comment by timothybrooks** [comment]
The sRGB color conversion matrix (CCM) I use is standard, and should work in the general case. For specific sensors, custom CCMs can be more accurate, however these are not always known or available.

What makes you believe the sRGB CCM is incorrect here? What do the images look like? If the colors are shifted, it may be an issue with the white balance gains or black and white levels.

**Comment by zhLawliet** [comment]
@timothybrooks thanks，i can get bp and wp values by dcraw -v -T, but can‘t get the CamRGB2XYZ,
such as
sRGB2XYZ = [0.4124564 0.3575761 0.1804375;0.2126729 0.7151522 0.0721750;0.0193339 0.1191920 0.9503041];
XYZ2Cam = [7171 -1986 -648;-8085 15555 2718;-2170 2512 7457]/10000;
the sRGB2XYZ is standard,but the XYZ2Cam is not, and there is no parameter in dcraw about Camera: google sailfish , so i  ask you about it . thank you very much.
