### ISSUE TITLE
Pink image

### ISSUE THREAD

**Issue by diwersan7** [timothybrooks/hdr-plus#11]
Hi! The only result I can get is completely pink image, could you point out what I did wrong?

**Comment by timothybrooks** [comment]
This is likely do to incorrect black and white levels, which I have hard-coded for my Canon 5D III. To correct this, you can find the black and white levels for your images inside their raw metadata.

**Comment by Trinkle23897** [comment]
@timothybrooks the pink result not only caused by bp and wp, but due to the dng format, the second green param in white balance param is set to 0. Should add "if (g1 == 0) g1 = g0;" into function "read_white_balance"

**Comment by timothybrooks** [comment]
Ah yes, thanks for pointing this out! I was unfamiliar with the g1=0 usage. Feel free to submit a pull request for this fix, if you would like :)

**Comment by Trinkle23897** [comment]
dcraw -v -T

**Comment by diwersan7** [comment]
Thank you!
