### ISSUE TITLE
Why is the result picture more blurred than the original picture?

### ISSUE THREAD

**Issue by whqwill** [timothybrooks/hdr-plus#13]
Why is the result picture more blurred than the original picture?

**Comment by timothybrooks** [comment]
The algorithm averages patches from different frames in order to decrease noise, however, in addition to decreasing noise, this can soften details (and cause artifacts) in some cases. If you provide the input images and result you are seeing, I could provide further insight.

**Comment by whqwill** [comment]
The following are original image and result @timothybrooks 

![0005_20170412_223424_01](https://user-images.githubusercontent.com/7381876/39794533-61d6f0da-537d-11e8-9e9e-86e95f9de225.JPG)

![result](https://user-images.githubusercontent.com/7381876/39794595-ae4c52d4-537d-11e8-8ea3-e5c9fe0827f4.jpg)

**Comment by timothybrooks** [comment]
The pipeline takes a burst of underexposed raw frames, whereas the original image you provided is a processed jpeg. Please provide the raw frames if you have them, otherwise, the pipeline is not expected to work for your application.

**Comment by timothybrooks** [comment]
There are a few things at play. First, this pipeline is for bursts of underexposed raw images. For it to provide benefit, you will need to use a sequence of raw images as input, not a single image.

Second, there are some weak points in my implementation, notably the demosaic algorithm that I use is not state-of-the-art, and I do not have any chromatic aberration suppression. These two factors, especially on the fisheye lens with strong distortion, causes the issues near edges.

Third, as with all raw image pipelines, color and lighting parameters must be tuned to provide the right look for a given camera. I tuned these variables to my Canon 5D III (and to my personal preferences), but feel free to change the compression factor, amount of contrast, white balance, etc.

I hope this helps, and I encourage you to take a look at my [writeup](http://timothybrooks.com/tech/hdr-plus/) if you have more specific questions about the algorithms I am using. If you have improvements, you are welcome to submit a pull request :)
