### ISSUE TITLE
Compile once and run more time

### ISSUE THREAD

**Issue by muhammadhemdan** [timothybrooks/hdr-plus#2]
Hi,
I need to run HDRPlus to process images in run time, so I need to compile it once not every time I give him new images. I knew two ways to do that:
1.    using compile_jit() once, then call realize() more time. But how can I do that in this project?
2.    using compile_to_file() but I don't know also how to do that with this project?

thanks,

**Comment by Titaniumtown** [comment]
Seems there isn't any activity here.
