### ISSUE TITLE
fix for darkareas missalignment

### ISSUE THREAD

**Issue by KillerInk** [timothybrooks/hdr-plus#21]
its simple but effective.
you have to add +64 to each input pixel and increase the blacklvl +64.
due that its easier for the algo to algin correct in dark areas, no more ghosting and visible tiles.

greets

**Comment by KillerInk** [comment]
Hi Timothy

i try to add it to your code, but its untested.

i only use the align and merge part and do it aot compile.
im including that complied lib in another project wich get the data direct from the camera and save it back as stacked dng.


also i think there is something wrong.

https://github.com/timothybrooks/hdr-plus/blob/bbcae37ffcc5cec4d3e7069bcab65b699659e57f/src/align.h#L7-L8

**Comment by KillerInk** [comment]
i wonder where that factor and the diff through 256 come from
https://github.com/timothybrooks/hdr-plus/blob/bbcae37ffcc5cec4d3e7069bcab65b699659e57f/src/merge.cpp#L52

https://github.com/timothybrooks/hdr-plus/blob/bbcae37ffcc5cec4d3e7069bcab65b699659e57f/src/merge.cpp#L58

orginal frame

![orginalframe](https://user-images.githubusercontent.com/30864229/46280873-5ac88d00-c56d-11e8-936b-defe7d8d9ed8.jpg)

with factor
![factor](https://user-images.githubusercontent.com/30864229/46280891-66b44f00-c56d-11e8-9b85-276d92937280.jpg)

factor removed

![removedfactor](https://user-images.githubusercontent.com/30864229/46280906-72077a80-c56d-11e8-87a1-50b3a3d76af5.jpg)

the factor seems to cause the ghosting in dark areas

**Comment by DanielMao2015** [comment]
@KillerInk hi, I am still confused about the effect of fact and the normailziation process. Can you help me?
