### ISSUE TITLE
Updating for better compatibility

### ISSUE THREAD

**Issue by Titaniumtown** [timothybrooks/hdr-plus#27]
Are you ever going to update this to work on newer halide versions? I never can get this to work even though I am following all the directions and I have spend hours trying to get it to compile. Please Help!!

**Comment by Titaniumtown** [comment]
I have sent some pull requests regarding issues people have been having and those pull requests should fix those issues (it did so with me).

**Comment by timothybrooks** [comment]
Thank you for the contributions! Sorry for the inconvenience--I no longer maintain this repository to avoid conflicts of interest as I now work on Google's HDR+. If you are interested in becoming a primary maintainer of this open source project, please let me know.
