### ISSUE TITLE
Move to cmake to improve compilation time

### ISSUE THREAD

**Issue by lamerman** [timothybrooks/hdr-plus#3]
Hi,
currently when you change one file the compilation takes quite a lot, because of the way make file is written. 
Have you considered moving to cmake?
I wrote a simple cmake file and here are results in terms of compilation speed when `HDRPlus.cpp` is changed:

current make
```
time make
g++ -O3 -g -Wall -std=c++11 HDRPlus.cpp align.cpp merge.cpp finish.cpp util.cpp -I/home/lamerman/work/hdr/halide//include -I/home/lamerman/work/hdr/halide//tools -lHalide -L/home/lamerman/work/hdr/halide//bin -lpng -o hdrplus

real    0m21.325s
user    0m20.300s
sys     0m0.972s
```

cmake (same compiler flags)

```
time make
Scanning dependencies of target hdrplus
[ 16%] Building CXX object CMakeFiles/hdrplus.dir/HDRPlus.cpp.o
[ 33%] Linking CXX executable hdrplus
[100%] Built target hdrplus

real    0m3.347s
user    0m3.064s
sys     0m0.228s
```

If it's fine for you I could provide a PR.

**Comment by timothybrooks** [comment]
This would be a great improvement! Please feel free to make a PR.

**Comment by lamerman** [comment]
Ok, I will make it in the middle of January. Currently quite far from my PC.
