### ISSUE TITLE
Supported file types

### ISSUE THREAD

**Issue by Titaniumtown** [timothybrooks/hdr-plus#31]
What file types can be the input? I know CR2 and dng. But what about tiff, jpg, png, etc? It seems the code might only support CR2 and dng but there are uncompressed tiffs as well.

**Comment by KillerInk** [comment]
the merge part expect 16bit bayer pattern with 4 colorchannels.
dng itself is a container based on tiff and can store alot different binarys.
aslong the input data is uncompressed 16bit cfa it should work.
i switched to libraw because it can output 16bit cfa from alot "RAW" files and you dont have to fight with the encoding

**Comment by Titaniumtown** [comment]
Where would one get this information on various uncompressed file formats with 16 bit cfa? Is there a singular site containing all of this information?

**Comment by Titaniumtown** [comment]
Would there be a way to use pngs, jpegs, etc as the input? Would that require heavy modification to the code?

**Comment by timothybrooks** [comment]
This pipeline is intended as a raw processing pipeline, meaning that it takes in raw images (those which have not yet been processed by any algorithms). A lot of the pipeline makes that assumption and is only useful in that case, and would therefore not work on jpgs, pngs, or other images which have already been processed.

Burst denoising of non-raw images is a fairly different problem, as it can't draw on the same assumptions about noise characteristics of linear data. In short, this pipeline (as-is) should only be used for processing raw photos, and would require significant work (possibly better as a separate repo) to denoise other image formats.

**Comment by Titaniumtown** [comment]
Thanks! That makes sense!
