### ISSUE TITLE
Input example

### ISSUE THREAD

**Issue by antoleb** [timothybrooks/hdr-plus#34]
Hi!
Could you please share an example of input files?

**Comment by Titaniumtown** [comment]
.dng and .CR2 files work for sure, but I don't know any more. There could be, but I do not know.

**Comment by Titaniumtown** [comment]
According to Timothy Brooks in the comment linked below, he says that only raw files would work (ex. dng, CR2, etc). If the raw image you input doesn't work you could convert it to a dng file.

Link to Timothy Brooks' Comment referenced above:
[https://github.com/timothybrooks/hdr-plus/issues/31#issuecomment-464519606](url)
