### ISSUE TITLE
Static hdrplus binary by replace dcraw

### ISSUE THREAD

**Issue by Titaniumtown** [timothybrooks/hdr-plus#37]
Any ideas on how to replace dcraw in order to create a static hdrplus binary?

The dcraw binary location is hard wired into the code, so in order to create a static binary the dependency on dcraw would have to be removed or fully incorporated into the final binary itself.

How would one go about this?
If this is achieved we could then have pre-compiled binaries on the release page!

**Comment by brotherofken** [comment]
Actually it should be possible to remove dcraw. Isn't it?

**Comment by Titaniumtown** [comment]
There is something in the HDRPlus.cpp file that referenced camera multipliers. And halide_load_raw.h also uses dcraw.

**Comment by Titaniumtown** [comment]
I am working on a prototype using libraw's "cam_mul[]"

**Comment by brotherofken** [comment]
Isn't it already done here? 
https://github.com/timothybrooks/hdr-plus/blob/master/src/InputSource.cpp#L22

**Comment by Titaniumtown** [comment]
Oh I am sorry I didn't see that part! Never mind then!

**Comment by Titaniumtown** [comment]
Wait... I found it used in halide_load_raw.h checking if the image can be read.

https://github.com/timothybrooks/hdr-plus/blob/master/src/halide_load_raw.h#L49

**Comment by Titaniumtown** [comment]
I have a prototype working; so stay tuned!

**Comment by Titaniumtown** [comment]
Ok I got it to work; I will commit it now!
