### ISSUE TITLE
 'halide_image_io.h' file not found

### ISSUE THREAD

**Issue by soham24** [timothybrooks/hdr-plus#42]
'halide_image_io.h' file not found

**Comment by brotherofken** [comment]
Hi!
Thank you for reporting. Could you provide more details, please, in order to help me to investigate:
0. Operation system
1. Halide and LLVM version
2. cmake command results and its logs.
3. make command results and its logs.
Please, use gist or other text storage to share long texts.

**Comment by soham24** [comment]
Sorry, it was my error. 
the tools directory did not compile at first. 
I did it in the second try. 
I am compiling it on mac.
