### ISSUE TITLE
Color correction

### ISSUE THREAD

**Issue by Haoban** [timothybrooks/hdr-plus#48]
Does anyone meet the problem with color correction? The output I got as .png format is so weird. I think it happens during tone mapping process.

**Comment by YiFabao** [comment]
I also meet the same problem

**Comment by Haoban** [comment]
> I also meet the same problem

If anyone solves this problem, PLEASE LET ME KNOW! Thanks!

**Comment by brotherofken** [comment]
There are many possible reasons for getting weird results. Most probably one of two things happened:
1. Wrong CFA pattern. AFAIK, current implementation supports RGGB layout. It's not hard to fix btw.
2. Wrong Color Correction Matrix, which is hardcoded here: https://github.com/timothybrooks/hdr-plus/blob/master/src/finish.cpp#L543

Could you upload your RAW and PNG files?

**Comment by Entropy512** [comment]
Yeah.  #39 will cause some really weird color issues for anything other than the Canon Tim developed with.

https://github.com/timothybrooks/hdr-plus/issues/44 is an alternative approach

**Comment by brotherofken** [comment]
@Haoban, could you check please if the aforementioned issues with color were resolved after merge of #54?

**Comment by Haoban** [comment]
> @Haoban, could you check please if the aforementioned color issues were resolved after merge of #54?

Thanks, I will check it. By the way, which directory I need to point as -DHALIDE_DISTRIB_DIR? Is Subdirectory bin or CMakeList file? I met this problem today when I tried it.

**Comment by brotherofken** [comment]
You have to point to the directory which contains `halide.cmake` file. It should be the directory where Halide was installed.
Just in case, here is the screenshot of directory contents:
![image](https://user-images.githubusercontent.com/9129106/76566556-152c2580-64be-11ea-9912-e6ea4e1b3360.png)

**Comment by YiFabao** [comment]
> @Haoban, could you check please if the aforementioned color issues were resolved after merge of #54?

I tried it on ubuntu 18.04 , it worked.Thanks!

**Comment by YiFabao** [comment]
In January of this year, I spent a lot of time transforming the code to generate code executable on Android. Today I was surprised to find that the author did the same work and changed it to a generator.
