### ISSUE TITLE
Wrong Halide Release

### ISSUE THREAD

**Issue by gcilli** [timothybrooks/hdr-plus#53]
In the README.md file, it is specified to download the "2017-06-03" release of Halide. However, according to the [historical release link](https://github.com/halide/Halide_old_history/releases), such release does not exists. The closest ones are:

 - 2017-10-30
 - 2017-05-03

Which release should be downloaded?

Thank you.

**Comment by brotherofken** [comment]
I tried the [latest Halide release](https://github.com/halide/Halide/releases/tag/release_2019_08_27) and it worked fine. [Master branch](https://github.com/halide/Halide/tree/master/) should work too.

**Comment by Titaniumtown** [comment]
Yea, the reason I put that was because it kept failing to compile. Then on the historical release link, they deleted the "2017-06-03" release, I have no idea why. I will update the read me if I can compile hdr-plus on the latest version of halide.

**Comment by Titaniumtown** [comment]
I have changed the readme to reflect this, issue should be solved. Thanks for bringing this to my attention!

**Comment by gcilli** [comment]
Thank you for the quick response. 

The latest Halide's release requires llvm 7.0 or greater. Which version of llvm did you use?

**Comment by gcilli** [comment]
I downloaded llvm 9.0 and everything compiled.
