### ISSUE TITLE
when I build the project use "cmake -DHALIDE_DISTRIB_DIR=$(Insert halide directory) ..", CMake Error at CMakeLists.txt:35 (halide_library):   Unknown CMake command "halide_library" appears why?

### ISSUE THREAD

**Issue by MingmChen** [timothybrooks/hdr-plus#57]

**Comment by chenmeiya** [comment]
hello, I also meet this problem. Could you help me to solve it? thanks.

**Comment by xuelimin** [comment]
when I meet this problem, I set some directories in the halide CMakeLists.txt, including two parts:`set(HALIDE_DISTRIB_DIR "/home/xlm/halide_build/distrib")`;`set(Halide_DIR "/home/xlm/Halide_old_history-release_2017_10_30")`,Halide_old_history-release_2017_10_30 just the source code, and halide_build is my make directory,hope you slove this pro.

**Comment by OPyshkin** [comment]
@xuelimin  this didn't help

**Comment by xuelimin** [comment]
邮件已查收，我会尽快回复您！

**Comment by OPyshkin** [comment]
@xuelimin thank you very much, i'll be waiting!
