### ISSUE TITLE
Assertion failed: (size == (size_t)type().bytes() && "Error: Overflow computing total size of buffer."),

### ISSUE THREAD

**Issue by YiFabao** [timothybrooks/hdr-plus#59]
I tried the newest code on my mac,  
when run the produced hdrplus binary , it crashed because of the following error:

 ./hdrplus dng_images dst.png payload_N000.dng payload_N001.dng payload_N002.dng
Opening dng_images/payload_N000.dng
Opening dng_images/payload_N001.dng
Opening dng_images/payload_N002.dng
Opening dng_images/payload_N003.dng
Opening dng_images/payload_N004.dng
Assertion failed: (size == (size_t)type().bytes() && "Error: Overflow computing total size of buffer."), function check_overflow, file /Users/yifabao/CLionProjects/Halide/include/Halide.h, line 5502.
Abort trap: 6

-------------------------------
My mac info : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

clang version 10.0.0
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

I don't know why ?

I debug found that in the code :
Halide::Runtime::Buffer<uint8_t> process() {
        const int width = burst.GetWidth(); // return -1
        const int height = burst.GetHeight();// return -1

Raws.empty()  == 1

and I tried on android , also make the same error 

![image](https://user-images.githubusercontent.com/8004601/79451946-f0c1ec80-8019-11ea-881f-e593be92ca5a.png)

**Comment by YiFabao** [comment]
I have soloved it!

**Comment by YiFabao** [comment]
I have successfully executed on android !
![image](https://user-images.githubusercontent.com/8004601/79460187-07227500-8027-11ea-9e9d-8b556a582780.png)

**Comment by f0enix** [comment]
@YiFabao how did you solve it?
