### ISSUE TITLE
The link for the examples not found error

### ISSUE THREAD

**Issue by ronsoohyeong** [timothybrooks/hdr-plus#61]
The link that contains HDR+ algorithm examples results in 404 Not Found error. 
https://drive.google.com/drive/folders/1XR61IhzuYQU5eLQfBJ0KEMK83Aocta6g?usp=sharing

Can you please check? Thanks in advance.

**Comment by Titaniumtown** [comment]
Sorry, I had to take it down because I didn't have enough space on my google drive :(

**Comment by Titaniumtown** [comment]
I can create a torrent if you want. I don't have any file sharing service. The files are pretty large.

**Comment by ronsoohyeong** [comment]
I think torrent may not pass the corporate firewall.. Can you please consider another file sharing service such as dropbox? Other candidates are in : https://www.lifewire.com/free-cloud-storage-1356638
