### ISSUE TITLE
Compilation issue: file not found: ./lib_halide_compiler_lib.a

### ISSUE THREAD

**Issue by kgmossey** [timothybrooks/hdr-plus#65]
When running make I get the following error.

[ 20%] Linking CXX executable halide_library_runtime.generator_binary
ld: file not found: ./lib_halide_compiler_lib.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [halide_library_runtime.generator_binary] Error 1
make[1]: *** [CMakeFiles/halide_library_runtime.generator_binary.dir/all] Error 2

Searching the web yields 0 results for lib_halide_compiler_lib.a, anywhere.  I see three references to the file in various link.txt files on my PC.  I successfully compiled halide prior to this, not sure what the issue is.

I'm using Mac OSX Catalina, clang 11.0.3, cmake 3.17.2, and the latest halide build.  LLVM is 10.0.0.

**Comment by Titaniumtown** [comment]
Try using the new compilation method using a nix development environment: #84
