### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by dongik86** [timothybrooks/hdr-plus#68]
I get the following error when trying to make hdr+.

(base) yoongyoo@PC1907057:~/test/hdrplus_c/build$ cmake -DHALIDE_DISTRIB_DIR="/home/yoongyoo/test/hdrplus_c/halide" ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HALIDE_DISTRIB_DIR: /home/yoongyoo/test/hdrplus_c/halide
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- run load halide cmake
-- Using /home/yoongyoo/test/hdrplus_c/halide/bin/libHalide.so
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.9")
-- Found tiffxx: /usr/lib/x86_64-linux-gnu/libtiffxx.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34")
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yoongyoo/test/hdrplus_c/build
(base) yoongyoo@PC1907057:~/test/hdrplus_c/build$ make -j$(expr $(nproc) \+ 1)
Scanning dependencies of target hdrplus_pipeline.generator_library
Scanning dependencies of target halide_library_runtime.generator_binary
Scanning dependencies of target align_and_merge.generator_library
[  3%] Building CXX object CMakeFiles/halide_library_runtime.generator_binary.dir/halide/tools/GenGen.cpp.o
[ 11%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/hdrplus_pipeline_generator.cpp.o
[ 11%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/align_and_merge_generator.cpp.o
[ 18%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/align.cpp.o
[ 18%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/align.cpp.o
[ 25%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/merge.cpp.o
[ 25%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/merge.cpp.o
[ 29%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/util.cpp.o
[ 33%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/util.cpp.o
[ 37%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/finish.cpp.o
/home/yoongyoo/test/hdrplus_c/src/align.cpp: In function ‘Halide::Func align(Halide::Func, Halide::Expr, Halide::Expr)’:
/home/yoongyoo/test/hdrplus_c/src/align.cpp:77:85: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, 0, width, 0, height);
                                                                                     ^
/home/yoongyoo/test/hdrplus_c/src/merge.cpp: In function ‘Halide::Func merge_temporal(Halide::Func, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Func)’:
/home/yoongyoo/test/hdrplus_c/src/merge.cpp:29:85: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, 0, width, 0, height);
                                                                                     ^
/home/yoongyoo/test/hdrplus_c/src/merge.cpp: In function ‘Halide::Func merge_temporal(Halide::Func, Halide::Expr, Halide::Expr, Halide::Expr, Halide::Func)’:
/home/yoongyoo/test/hdrplus_c/src/merge.cpp:29:85: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, 0, width, 0, height);
                                                                                     ^
In file included from /home/yoongyoo/test/hdrplus_c/src/align.h:12:0,
                 from /home/yoongyoo/test/hdrplus_c/src/align.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
In file included from /home/yoongyoo/test/hdrplus_c/src/merge.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/merge.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
In file included from /home/yoongyoo/test/hdrplus_c/src/merge.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/merge.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
/home/yoongyoo/test/hdrplus_c/src/align.cpp:117:92: warning: ‘Halide::Func Halide::BoundaryConditions::repeat_edge(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func alignment_repeat = BoundaryConditions::repeat_edge(alignment, 0, num_tx, 0, num_ty);
                                                                                            ^
/home/yoongyoo/test/hdrplus_c/src/finish.cpp: In function ‘Halide::Func demosaic(Halide::Func, Halide::Expr, Halide::Expr)’:
/home/yoongyoo/test/hdrplus_c/src/finish.cpp:90:87: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func input_mirror = BoundaryConditions::mirror_interior(input, 0, width, 0, height);
                                                                                       ^
/home/yoongyoo/test/hdrplus_c/src/align.cpp: In function ‘Halide::Func align(Halide::Func, Halide::Expr, Halide::Expr)’:
/home/yoongyoo/test/hdrplus_c/src/align.cpp:77:85: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func imgs_mirror = BoundaryConditions::mirror_interior(imgs, 0, width, 0, height);
                                                                                     ^
In file included from /home/yoongyoo/test/hdrplus_c/src/align.h:12:0,
                 from /home/yoongyoo/test/hdrplus_c/src/align.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18509:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func repeat_edge(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~
In file included from /home/yoongyoo/test/hdrplus_c/src/finish.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/finish.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
In file included from /home/yoongyoo/test/hdrplus_c/src/align.h:12:0,
                 from /home/yoongyoo/test/hdrplus_c/src/align.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
/home/yoongyoo/test/hdrplus_c/src/align.cpp:117:92: warning: ‘Halide::Func Halide::BoundaryConditions::repeat_edge(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func alignment_repeat = BoundaryConditions::repeat_edge(alignment, 0, num_tx, 0, num_ty);
                                                                                            ^
/home/yoongyoo/test/hdrplus_c/src/finish.cpp: In function ‘Halide::Func bilateral_filter(Halide::Func, Halide::Expr, Halide::Expr)’:
/home/yoongyoo/test/hdrplus_c/src/finish.cpp:200:87: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_interior(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func input_mirror = BoundaryConditions::mirror_interior(input, 0, width, 0, height);
                                                                                       ^
In file included from /home/yoongyoo/test/hdrplus_c/src/align.h:12:0,
                 from /home/yoongyoo/test/hdrplus_c/src/align.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18509:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func repeat_edge(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~
In file included from /home/yoongyoo/test/hdrplus_c/src/finish.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/finish.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18632:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_interior(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~~~~
/home/yoongyoo/test/hdrplus_c/src/finish.cpp: In function ‘Halide::Func desaturate_noise(Halide::Func, Halide::Expr, Halide::Expr)’:
/home/yoongyoo/test/hdrplus_c/src/finish.cpp:254:84: warning: ‘Halide::Func Halide::BoundaryConditions::mirror_image(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func input_mirror = BoundaryConditions::mirror_image(input, 0, width, 0, height);
                                                                                    ^
In file included from /home/yoongyoo/test/hdrplus_c/src/finish.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/finish.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18589:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func mirror_image(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~~
/home/yoongyoo/test/hdrplus_c/src/finish.cpp: In function ‘Halide::Func combine(Halide::Func, Halide::Func, Halide::Expr, Halide::Expr, Halide::Func)’:
/home/yoongyoo/test/hdrplus_c/src/finish.cpp:350:80: warning: ‘Halide::Func Halide::BoundaryConditions::repeat_edge(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func im1_mirror = BoundaryConditions::repeat_edge(im1, 0 , width, 0, height);
                                                                                ^
In file included from /home/yoongyoo/test/hdrplus_c/src/finish.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/finish.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18509:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func repeat_edge(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~
/home/yoongyoo/test/hdrplus_c/src/finish.cpp:351:80: warning: ‘Halide::Func Halide::BoundaryConditions::repeat_edge(const T&, Bounds&& ...) [with T = Halide::Func; Bounds = {int, Halide::Expr&, int, Halide::Expr&}; typename std::enable_if<Halide::Internal::all_are_convertible<Halide::Expr, Bounds ...>::value>::type* <anonymous> = 0]’ is deprecated: Add braces around the bounds like so: {{a, b}, {c, d}} [-Wdeprecated-declarations]
     Func im2_mirror = BoundaryConditions::repeat_edge(im2, 0 , width, 0, height);
                                                                                ^
In file included from /home/yoongyoo/test/hdrplus_c/src/finish.h:4:0,
                 from /home/yoongyoo/test/hdrplus_c/src/finish.cpp:1:
/home/yoongyoo/test/hdrplus_c/halide/include/Halide.h:18509:33: note: declared here
 HALIDE_NO_USER_CODE_INLINE Func repeat_edge(const T &func_like, Bounds &&... bounds) {
                                 ^~~~~~~~~~~
[ 40%] Linking CXX executable halide_library_runtime.generator_binary
[ 40%] Built target halide_library_runtime.generator_binary
Scanning dependencies of target halide_rt_host_runtime_gen
[ 44%] Linking CXX static library libalign_and_merge.generator_library.a
[ 44%] Built target align_and_merge.generator_library
Scanning dependencies of target align_and_merge.generator_binary
[ 48%] Building CXX object CMakeFiles/align_and_merge.generator_binary.dir/halide/tools/GenGen.cpp.o
[ 51%] Linking CXX static library libhdrplus_pipeline.generator_library.a
[ 51%] Built target hdrplus_pipeline.generator_library
Scanning dependencies of target hdrplus_pipeline.generator_binary
[ 55%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_binary.dir/halide/tools/GenGen.cpp.o
[ 55%] Built target halide_rt_host_runtime_gen
[ 59%] Linking CXX executable align_and_merge.generator_binary
[ 59%] Built target align_and_merge.generator_binary
[ 62%] Linking CXX executable hdrplus_pipeline.generator_binary
Scanning dependencies of target align_and_merge_lib_gen
Unknown flag: -x
gengen
  [-g GENERATOR_NAME] [-f FUNCTION_NAME] [-o OUTPUT_DIR] [-r RUNTIME_NAME] [-d 1|0]
  [-e EMIT_OPTIONS] [-n FILE_BASE_NAME] [-p PLUGIN_NAME] [-s AUTOSCHEDULER_NAME]
       target=target-string[,target-string...] [generator_arg=value [...]]

 -d  Build a module that is suitable for using for gradient descent calculationn
     in TensorFlow or PyTorch. See Generator::build_gradient_module() documentation.

 -e  A comma separated list of files to emit. Accepted values are:
     [assembly, bitcode, c_header, c_source, cpp_stub, featurization,
      llvm_assembly, object, python_extension, pytorch_wrapper, registration,
      schedule, static_library, stmt, stmt_html, compiler_log].
     If omitted, default value is [c_header, static_library, registration].

 -p  A comma-separated list of shared libraries that will be loaded before the
     generator is run. Useful for custom auto-schedulers. The generator must
     either be linked against a shared libHalide or compiled with -rdynamic
     so that references in the shared library to libHalide can resolve.
     (Note that this does not change the default autoscheduler; use the -s flag
     to set that value.)
 -r   The name of a standalone runtime to generate. Only honors EMIT_OPTIONS 'o'
     and 'static_library'. When multiple targets are specified, it picks a
     runtime that is compatible with all of the targets, or fails if it cannot
     find one. Flags across all of the targets that do not affect runtime code
     generation, such as `no_asserts` and `no_runtime`, are ignored.

 -s  The name of an autoscheduler to set as the default.
CMakeFiles/align_and_merge_lib_gen.dir/build.make:62: recipe for target 'genfiles/align_and_merge/align_and_merge.a' failed
make[2]: *** [genfiles/align_and_merge/align_and_merge.a] Error 1
CMakeFiles/Makefile2:245: recipe for target 'CMakeFiles/align_and_merge_lib_gen.dir/all' failed
make[1]: *** [CMakeFiles/align_and_merge_lib_gen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 62%] Built target hdrplus_pipeline.generator_binary
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Titaniumtown** [comment]
Please try with the new compilation instructions: #84
