### ISSUE TITLE
build error!!!!   anyone can help me?

### ISSUE THREAD

**Issue by zhangpengk** [timothybrooks/hdr-plus#73]
(base) zhangp@zhangp:~/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/bin/libHalide.so
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.9")  
-- Found tiffxx: /usr/lib/x86_64-linux-gnu/libtiffxx.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/build

(base) zhangp@zhangp:~/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/build$ make -j8
Scanning dependencies of target hdrplus_pipeline.generator_library
Scanning dependencies of target halide_library_runtime.generator_binary
Scanning dependencies of target align_and_merge.generator_library
[  3%] Building CXX object CMakeFiles/halide_library_runtime.generator_binary.dir/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/tools/GenGen.cpp.o
[  7%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/align_and_merge_generator.cpp.o
[ 11%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/merge.cpp.o
[ 14%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/align.cpp.o
[ 18%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/hdrplus_pipeline_generator.cpp.o
[ 25%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/align.cpp.o
[ 25%] Building CXX object CMakeFiles/align_and_merge.generator_library.dir/src/util.cpp.o
[ 29%] Building CXX object CMakeFiles/hdrplus_pipeline.generator_library.dir/src/merge.cpp.o
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.cpp: In function ‘Halide::Func gauss_down4(Halide::Func, std::__cxx11::string)’:
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.cpp:41:25: error: no matching function for call to ‘Halide::Buffer<unsigned int>::translate(<brace-enclosed initializer list>)’
     k.translate({-2, -2});
                         ^
In file included from /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.h:4:0,
                 from /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.cpp:1:

....
....
....
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:6273:27: error: no matching function for call to ‘Halide::Runtime::Buffer<float, 4>::translate()’
     HALIDE_BUFFER_FORWARD(translate)
                           ^
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:6238:10: note: in definition of macro ‘HALIDE_BUFFER_FORWARD’
     auto method(Args&&... args) ->                                      \
          ^~~~~~
In file included from /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.h:4:0,
                 from /home/zhangp/Desktop/image-fusion/hdr/hdr-plus/hdr-plus-master/src/util.cpp:1:
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:4668:10: note: candidate: void Halide::Runtime::Buffer<T, D>::translate(int, int) [with T = float; int D = 4]
     void translate(int d, int delta) {
          ^~~~~~~~~
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:4668:10: note:   candidate expects 2 arguments, 0 provided
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:4682:10: note: candidate: void Halide::Runtime::Buffer<T, D>::translate(const std::vector<int>&) [with T = float; int D = 4]
     void translate(const std::vector<int> &delta) {
          ^~~~~~~~~
/home/zhangp/Desktop/image-fusion/hdr/hdr-plus/halide_build/distrib/include/Halide.h:4682:10: note:   candidate expects 1 argument, 0 provided
[ 40%] Built target halide_rt_host_runtime_gen
CMakeFiles/hdrplus_pipeline.generator_library.dir/build.make:120: recipe for target 'CMakeFiles/hdrplus_pipeline.generator_library.dir/src/finish.cpp.o' failed
make[2]: *** [CMakeFiles/hdrplus_pipeline.generator_library.dir/src/finish.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/hdrplus_pipeline.generator_library.dir/build.make:133: recipe for target 'CMakeFiles/hdrplus_pipeline.generator_library.dir/src/util.cpp.o' failed
make[2]: *** [CMakeFiles/hdrplus_pipeline.generator_library.dir/src/util.cpp.o] Error 1
CMakeFiles/Makefile2:476: recipe for target 'CMakeFiles/hdrplus_pipeline.generator_library.dir/all' failed
make[1]: *** [CMakeFiles/hdrplus_pipeline.generator_library.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ersanliqiao** [comment]
same error

**Comment by Titaniumtown** [comment]
Fixed in: #84
