### ISSUE TITLE
build error!!!! On macOS Big Sur Intel

### ISSUE THREAD

**Issue by tgsqq** [timothybrooks/hdr-plus#74]
> mac@MacdeMacBook-Pro build % cmake -DHALIDE_DISTRIB_DIR=$(Insert halide directory) ..
zsh: command not found: Insert
-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Found LibXml2: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libxml2.tbd (found version "2.9.4") 
-- Halide detected current CMake target:  x86-64-osx
-- Halide using default generator target: host
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37") 
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "90") 
-- Found TIFF: /usr/local/lib/libtiff.dylib (found version "4.3.0")  
-- Found tiffxx: /usr/local/lib/libtiffxx.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mac/Data/hdr-plus/build

> mac@MacdeMacBook-Pro build % make -j$(expr $(nproc) \+ 1)
zsh: command not found: nproc
expr: syntax error
[  3%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/align.cpp.o
[ 12%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/merge.cpp.o
[ 12%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/util.cpp.o
[ 12%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/finish.cpp.o
[ 24%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/util.cpp.o
[ 33%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/align_and_merge_generator.cpp.o
[ 33%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/usr/local/share/tools/GenGen.cpp.o
[ 33%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/merge.cpp.o
[ 33%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/align.cpp.o
[ 33%] Building CXX object CMakeFiles/align_and_merge_generator.dir/usr/local/share/tools/GenGen.cpp.o
[ 33%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/hdrplus_pipeline_generator.cpp.o
2 warnings generated.
2 warnings generated.
1 warning generated.
1 warning generated.
[ 36%] Linking CXX executable align_and_merge_generator
[ 36%] Built target align_and_merge_generator
5 warnings generated.
[ 39%] Generating align_and_merge.runtime.o
[ 42%] Generating align_and_merge.h, align_and_merge.o
[ 45%] Linking CXX executable hdrplus_pipeline_generator
[ 45%] Built target hdrplus_pipeline_generator
[ 48%] Generating hdrplus_pipeline.runtime.o
[ 51%] Generating hdrplus_pipeline.h, hdrplus_pipeline.o
Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.
make[2]: *** [align_and_merge.h] Error 255
make[1]: *** [CMakeFiles/align_and_merge.update.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX static library libalign_and_merge.runtime.a
[ 54%] Built target align_and_merge.runtime
[ 57%] Linking CXX static library libhdrplus_pipeline.runtime.a
[ 57%] Built target hdrplus_pipeline.runtime
Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.
make[2]: *** [hdrplus_pipeline.h] Error 255
make[1]: *** [CMakeFiles/hdrplus_pipeline.update.dir/all] Error 2
make: *** [all] Error 2

**Comment by tgsqq** [comment]
> mac@MacdeMacBook-Pro build % cmake -DHALIDE_DISTRIB_DIR=/usr/local/Cellar/halide/11.0.1_1 ..
-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Found LibXml2: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libxml2.tbd (found version "2.9.4") 
-- Halide detected current CMake target:  x86-64-osx
-- Halide using default generator target: host
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37") 
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "90") 
-- Found TIFF: /usr/local/lib/libtiff.dylib (found version "4.3.0")  
-- Found tiffxx: /usr/local/lib/libtiffxx.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mac/Data/hdr-plus/build
mac@MacdeMacBook-Pro build % make -j8
[  9%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/finish.cpp.o
[  9%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/merge.cpp.o
[ 15%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/align_and_merge_generator.cpp.o
[ 15%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/merge.cpp.o
[ 15%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/hdrplus_pipeline_generator.cpp.o
[ 18%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/util.cpp.o
[ 21%] Building CXX object CMakeFiles/align_and_merge_generator.dir/src/align.cpp.o
[ 24%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/align.cpp.o

> 2 warnings generated.
1 warning generated.
[ 30%] Building CXX object CMakeFiles/align_and_merge_generator.dir/usr/local/Cellar/halide/11.0.1_1/share/tools/GenGen.cpp.o
[ 30%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/src/util.cpp.o
2 warnings generated.
[ 33%] Building CXX object CMakeFiles/hdrplus_pipeline_generator.dir/usr/local/Cellar/halide/11.0.1_1/share/tools/GenGen.cpp.o
1 warning generated.
5 warnings generated.
[ 36%] Linking CXX executable align_and_merge_generator
[ 36%] Built target align_and_merge_generator
[ 39%] Generating align_and_merge.runtime.o
[ 42%] Generating align_and_merge.h, align_and_merge.o
[ 45%] Linking CXX executable hdrplus_pipeline_generator
[ 45%] Built target hdrplus_pipeline_generator
[ 48%] Generating hdrplus_pipeline.runtime.o
[ 51%] Generating hdrplus_pipeline.h, hdrplus_pipeline.o
**Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.**

> make[2]: *** [align_and_merge.h] Error 255
make[1]: *** [CMakeFiles/align_and_merge.update.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX static library libalign_and_merge.runtime.a
[ 54%] Built target align_and_merge.runtime
[ 57%] Linking CXX static library libhdrplus_pipeline.runtime.a
[ 57%] Built target hdrplus_pipeline.runtime
**Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.**

> make[2]: *** [hdrplus_pipeline.h] Error 255

> make[1]: *** [CMakeFiles/hdrplus_pipeline.update.dir/all] Error 2

> make: *** [all] Error 2

**Comment by tgsqq** [comment]
Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.

**Comment by lulala1126** [comment]
I have same error... are you finish it?

**Comment by OPNA2608** [comment]
> `-DHALIDE_DISTRIB_DIR=/usr/local/Cellar/halide/11.0.1_1 ..`

Try building with Halide 10.

**Comment by Zhang-Setsail** [comment]
> > `-DHALIDE_DISTRIB_DIR=/usr/local/Cellar/halide/11.0.1_1 ..`
> 
> Try building with Halide 10.

Still have this problem with halide 10 :(

**Comment by Titaniumtown** [comment]
Working on fixing this as a part of fixing #82
