### ISSUE TITLE
Cmake: Could not find a package configuration file provided by "Halide"

### ISSUE THREAD

**Issue by Abdob** [timothybrooks/hdr-plus#78]
I am using Ubuntu 20.04 and have tried different versions of llvm and halide. I haven't been able to compile this program.

I am building llvm like this:
git clone https://github.com/llvm/llvm-project.git
git checkout release/9.x  # to build LLVM 9.x
cd llvm-project
mkdir build
cd build
cmake -DLLVM_ENABLE_PROJECTS="clang;lld" -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD="X86;ARM;NVPTX;AArch64;Mips;PowerPC" -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_32_BITS=OFF ../llvm
 make -j 4
 
and building halide like this:
export LLVM_CONFIG=/home/wave/hdr/llvm-install/bin/llvm-config
cd Halide
build

When I try to compile hdr-plus with:
mkdir build
cd build
cmake -DHALIDE_DISTRIB_DIR=/home/wave/hdr/Halide/distrib ..

I get :
CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindHalide.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Halide", but
  CMake did not find one.

  Could not find a package configuration file provided by "Halide" with any
  of the following names:

    HalideConfig.cmake
    halide-config.cmake

  Add the installation prefix of "Halide" to CMAKE_PREFIX_PATH or set
  "Halide_DIR" to a directory containing one of the above files.  If "Halide"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by OPyshkin** [comment]
Did you manage to solve it? I currently have the same issue

**Comment by OPyshkin** [comment]
I've tried setting path to /distrib/ directory in CMakeLists.txt, but it didn't help

**Comment by Abdob** [comment]
No I have not solved it. I tried many combinations of llvm/halide/hdr-plus versions. I might try using a different Ubuntu distro.

**Comment by Titaniumtown** [comment]
I recommend using nix to compile hdr-plus as it will generate the correct development environment.

Checkout the new compilation instructions: #84
