### ISSUE TITLE
How can I get the data?

### ISSUE THREAD

**Issue by JinliEmma** [timothybrooks/hdr-plus#80]

**Comment by JinliEmma** [comment]
http://www.gardling.com/hdr_plus ，this utl can't visit. Can you share the dataset by other ways?

**Comment by Titaniumtown** [comment]
> http://www.gardling.com/hdr_plus ，this utl can't visit. Can you share the dataset by other ways?

fixed

**Comment by Harold2017** [comment]
Hi, your link broken again
